export const HOME = '/'
export const LOGIN = '/login'
export const REGISTER = '/register'
export const REGISTER_COMPLETE = '/register/complete'
export const FORGOT_PASSWORD = '/forgot/password'

export const ADMIN_DASHBOARD = '/admin/dashboard'
export const ADMIN_PRODUCT = '/admin/create-product'
export const ADMIN_SINGLE_PRODUCT = '/admin/product'
export const ADMIN_PRODUCTS = '/admin/products'
export const ADMIN_CATEGORIES = '/admin/categories'
export const ADMIN_SUB = '/admin/sub'
export const ADMIN_COUPONS = '/admin/coupons'
export const ADMIN_UPDATE_CATEGORY = '/admin/category'
export const ADMIN_UPDATE_SUB = '/admin/sub'

export const PRODUCT = '/product'

export const USER_HISTORY = '/user/history'
export const USER_PASSWORD = '/user/password'
export const USER_WISHLIST = '/user/wishlist'
